// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.test.rmi.chat.server;

public final class ChatServer_Stub
    extends java.rmi.server.RemoteStub
    implements com.test.rmi.chat.ChatServerInf, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_exitChat_0;
    private static java.lang.reflect.Method $method_getChatList_1;
    private static java.lang.reflect.Method $method_joinChat_2;
    private static java.lang.reflect.Method $method_makeNewChat_3;
    private static java.lang.reflect.Method $method_setMessage_4;
    
    static {
	try {
	    $method_exitChat_0 = com.test.rmi.chat.ChatServerInf.class.getMethod("exitChat", new java.lang.Class[] {java.lang.String.class, com.test.rmi.chat.ChatClientInf.class});
	    $method_getChatList_1 = com.test.rmi.chat.ChatServerInf.class.getMethod("getChatList", new java.lang.Class[] {});
	    $method_joinChat_2 = com.test.rmi.chat.ChatServerInf.class.getMethod("joinChat", new java.lang.Class[] {java.lang.String.class, com.test.rmi.chat.ChatClientInf.class});
	    $method_makeNewChat_3 = com.test.rmi.chat.ChatServerInf.class.getMethod("makeNewChat", new java.lang.Class[] {java.lang.String.class});
	    $method_setMessage_4 = com.test.rmi.chat.ChatServerInf.class.getMethod("setMessage", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ChatServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of exitChat(String, ChatClientInf)
    public void exitChat(java.lang.String $param_String_1, com.test.rmi.chat.ChatClientInf $param_ChatClientInf_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_exitChat_0, new java.lang.Object[] {$param_String_1, $param_ChatClientInf_2}, -1328343735655372598L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getChatList()
    public java.util.List getChatList()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getChatList_1, null, 6775340121585372894L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of joinChat(String, ChatClientInf)
    public void joinChat(java.lang.String $param_String_1, com.test.rmi.chat.ChatClientInf $param_ChatClientInf_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_joinChat_2, new java.lang.Object[] {$param_String_1, $param_ChatClientInf_2}, 3484391401919411309L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of makeNewChat(String)
    public boolean makeNewChat(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_makeNewChat_3, new java.lang.Object[] {$param_String_1}, -7125952063864436699L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setMessage(String, String)
    public void setMessage(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setMessage_4, new java.lang.Object[] {$param_String_1, $param_String_2}, 3352804270881037342L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
